import { Credits } from '@core/models/credits';
import { TmdbApiGetResponse } from '@core/models/tmdb-api-get-response';
import { TvShow } from '@core/models/tv-show';
import { TvShowDetails } from '@core/models/tv-show-details';

export const TvShowsResultsMock: TmdbApiGetResponse<TvShow> = {
  page: 1,
  results: [
    {
      backdrop_path: '/7q448EVOnuE3gVAx24krzO7SNXM.jpg',
      first_air_date: '2021-09-03',
      genre_ids: [10764],
      id: 130392,
      name: "The D'Amelio Show",
      origin_country: ['US'],
      original_language: 'en',
      original_name: "The D'Amelio Show",
      overview:
        'From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.',
      popularity: 25.211,
      poster_path: '/z0iCS5Znx7TeRwlYSd4c01Z0lFx.jpg',
      vote_average: 9.4,
      vote_count: 2620,
    },
    {
      backdrop_path: null,
      first_air_date: '2004-05-10',
      genre_ids: [16, 35],
      id: 100,
      name: 'I Am Not an Animal',
      origin_country: ['GB'],
      original_language: 'en',
      original_name: 'I Am Not an Animal',
      overview:
        'I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.',
      popularity: 16.402,
      poster_path: '/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg',
      vote_average: 9.2,
      vote_count: 690,
    },
    {
      backdrop_path: '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
      first_air_date: '2021-11-06',
      genre_ids: [16, 10765, 10759, 18],
      id: 94605,
      name: 'Arcane',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Arcane',
      overview:
        'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
      popularity: 350.961,
      poster_path: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
      vote_average: 9.1,
      vote_count: 1630,
    },
    {
      backdrop_path: '/c8dm74uPCMA27iKAR1WnHKTsI9h.jpg',
      first_air_date: '2015-08-01',
      genre_ids: [10764],
      id: 77696,
      name: 'Run BTS!',
      origin_country: ['KR'],
      original_language: 'ko',
      original_name: '달려라 방탄!',
      overview:
        'Run BTS! is a South Korean show by the boy band BTS. The show is all about BTS doing activities, challenges and lots more.',
      popularity: 28.964,
      poster_path: '/xxv8Ibs8Anni6qrWkAf60rDsPCu.jpg',
      vote_average: 9,
      vote_count: 237,
    },
    {
      backdrop_path: '/7gbmM2NWcqZONbp65HUWDf4wr0Q.jpg',
      first_air_date: '2019-07-12',
      genre_ids: [16, 18],
      id: 88040,
      name: 'Given',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: 'ギヴン',
      overview:
        "Tightly clutching his Gibson guitar, Mafuyu Satou steps out of his dark apartment to begin another day of his high school life. While taking a nap in a quiet spot on the gymnasium staircase, he has a chance encounter with fellow student Ritsuka Uenoyama, who berates him for letting his guitar's strings rust and break. Noticing Uenoyama's knowledge of the instrument, Satou pleads for him to fix it and to teach him how to play. Uenoyama eventually agrees and invites him to sit in on a jam session with his two band mates: bassist Haruki Nakayama and drummer Akihiko Kaji.",
      popularity: 51.499,
      poster_path: '/pdDCcAq8RNSZNk81PXYoHNUPHjn.jpg',
      vote_average: 9,
      vote_count: 576,
    },
    {
      backdrop_path: '/hqFaSNICeh0Y3Hp0gtEIzDBmUVo.jpg',
      first_air_date: '2020-08-19',
      genre_ids: [10764],
      id: 106600,
      name: 'BTS In the SOOP',
      origin_country: ['KR'],
      original_language: 'ko',
      original_name: 'In the SOOP BTS편',
      overview:
        "'In the SOOP BTS ver.' is a reality show, portraying BTS members' everyday life, relaxation, and everything in between, away from the city life. A time of freedom and healing in a place for BTS, and BTS only.",
      popularity: 16.366,
      poster_path: '/eBsIEKqLMtktw2jpFPa9WTuGyPN.jpg',
      vote_average: 9,
      vote_count: 256,
    },
    {
      backdrop_path: '/3C9PgPZxmECrNZGqOU5ssnESANT.jpg',
      first_air_date: '2021-07-01',
      genre_ids: [18],
      id: 125910,
      name: 'Young Royals',
      origin_country: ['SE'],
      original_language: 'sv',
      original_name: 'Young Royals',
      overview:
        'Prince Wilhelm adjusts to life at his prestigious new boarding school, Hillerska, but following his heart proves more challenging than anticipated.',
      popularity: 57.106,
      poster_path: '/6CHznbr0BF78ar16zJwTVRYLLOX.jpg',
      vote_average: 8.9,
      vote_count: 556,
    },
    {
      backdrop_path: '/qSgBzXdu6QwVVeqOYOlHolkLRxZ.jpg',
      first_air_date: '2019-01-09',
      genre_ids: [16, 10759, 10765, 18],
      id: 83095,
      name: 'The Rising of the Shield Hero',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '盾の勇者の成り上がり',
      overview:
        "Iwatani Naofumi was summoned into a parallel world along with 3 other people to become the world's Heroes. Each of the heroes respectively equipped with their own legendary equipment when summoned, Naofumi received the Legendary Shield as his weapon. Due to Naofumi's lack of charisma and experience he's labeled as the weakest, only to end up betrayed, falsely accused, and robbed by on the third day of adventure. Shunned by everyone from the king to peasants, Naofumi's thoughts were filled with nothing but vengeance and hatred. Thus, his destiny in a parallel World begins...",
      popularity: 71.549,
      poster_path: '/hm7AAWOMNxGzpGolgzNATgnyQbb.jpg',
      vote_average: 8.9,
      vote_count: 757,
    },
    {
      backdrop_path: '/ohOrfdh80HVY5QBD8kV2FYYSVwF.jpg',
      first_air_date: '2021-01-10',
      genre_ids: [16, 10759],
      id: 110309,
      name: 'SK8 the Infinity',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: 'SK∞ エスケーエイト',
      overview:
        '"S" is a dangerous, top secret, no-holds-barred downhill skateboarding race down an abandoned mine. When avid skateboarder Reki takes Langa to the mountain where "S" is held, Langa, who\'s never been on a skateboard in his life, finds himself sucked into the world of "S", and…?!',
      popularity: 101.021,
      poster_path: '/ksb6QlSCsRLr3MNmxc8ojOOLK6V.jpg',
      vote_average: 8.9,
      vote_count: 184,
    },
    {
      backdrop_path: '/uAjMQlbPkVHmUahhCouANlHSDW2.jpg',
      first_air_date: '2019-01-11',
      genre_ids: [16, 9648, 10765, 10759, 18],
      id: 83097,
      name: 'The Promised Neverland',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '約束のネバーランド',
      overview:
        'Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their "Mama," Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage — a rule they are expected to follow no matter what. However, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family... never to be heard from again.\n\nHowever, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.',
      popularity: 90.773,
      poster_path: '/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg',
      vote_average: 8.9,
      vote_count: 753,
    },
    {
      backdrop_path: '/2f8OLO6UYp78dIQMs0oi7ja15Bl.jpg',
      first_air_date: '2010-04-02',
      genre_ids: [16, 35, 18],
      id: 65648,
      name: 'Maid Sama!',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '会長はメイド様！',
      overview:
        'Misaki Ayuzawa is the first female student council president at a once all-boys school turned co-ed. She rules the school with strict discipline demeanor. But she has a secret—she works at a maid cafe due to her families circumstances. One day the popular A-student and notorious heart breaker Takumi Usui finds out her secret and makes a deal with her to keep it hush from the school in exchange for spending some time with him.',
      popularity: 38.856,
      poster_path: '/igkn0M1bgMeATz59LShvVxZNdVd.jpg',
      vote_average: 8.9,
      vote_count: 429,
    },
    {
      backdrop_path: '/ci7jTekDFEx6U48XUCl3vBMdrns.jpg',
      first_air_date: '2018-07-06',
      genre_ids: [10759, 18, 9648, 16],
      id: 80564,
      name: 'Banana Fish',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: 'バナナフィッシュ',
      overview:
        "Nature made Ash Lynx beautiful; nurture made him a cold ruthless killer. A runaway brought up as the adopted heir and sex toy of \"Papa\" Dino Golzine, Ash, now at the rebellious age of seventeen, forsakes the kingdom held out by the devil who raised him. But the hideous secret that drove Ash's older brother mad in Vietnam has suddenly fallen into Papa's insatiably ambitious hands—and it's exactly the wrong time for Eiji Okamura, a pure-hearted young photographer from Japan, to make Ash Lynx's acquaintance...",
      popularity: 59.414,
      poster_path: '/1UV5di9UIXwrpCW3xQ4RNli5hEV.jpg',
      vote_average: 8.9,
      vote_count: 649,
    },
    {
      backdrop_path: '/x6jWDL4H9TaBLGEvyej0qKiirBU.jpg',
      first_air_date: '2014-10-10',
      genre_ids: [16, 35, 18],
      id: 61663,
      name: 'Your Lie in April',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '四月は君の嘘',
      overview:
        "Kousei Arima was a genius pianist until his mother's sudden death took away his ability to play. Each day was dull for Kousei. But, then he meets a violinist named Kaori Miyazono who has an eccentric playing style. Can the heartfelt sounds of the girl's violin lead the boy to play the piano again?",
      popularity: 58.787,
      poster_path: '/IGbeFv5Ji4W0x530JcSHiQpamY.jpg',
      vote_average: 8.9,
      vote_count: 628,
    },
    {
      backdrop_path: '/1ejS56lC8db62IKVj1pTQlfAEQy.jpg',
      first_air_date: '2018-09-13',
      genre_ids: [10759, 16, 18, 10751],
      id: 123566,
      name: 'Metal Family',
      origin_country: ['RU'],
      original_language: 'ko',
      original_name: 'Metal Family',
      overview:
        'Metal Family follows the daily lives of Glam and Victoria, two metal fans that fell in love and had two children together, Dee and Heavy.',
      popularity: 46.981,
      poster_path: '/yovTSLBdNjXIVo8CPaPWFE5NcAw.jpg',
      vote_average: 8.9,
      vote_count: 271,
    },
    {
      backdrop_path: '/sWghoJDqMRHDnkmk7fr3By5XPnf.jpg',
      first_air_date: '2019-10-05',
      genre_ids: [16, 35, 10765],
      id: 91801,
      name: 'Welcome to Demon School! Iruma-kun',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '魔入りました！入間くん',
      overview:
        'Fourteen-year-old Suzuki Iruma has just been abandoned and sold to a demon by his irresponsible parents! Surprisingly, the next thing he knows he\'s living with the demon who has adopted him as his new grandson, and has been transferred into a school in the demon world where his new "demon" grandfather works as the principal. Thus begins the cowardly Iruma-kun\'s extraordinary school life among the otherworldly as he faces his true self, takes on challenges, and rises to become someone great.',
      popularity: 83.974,
      poster_path: '/aed6I1EMR4Lbk8bdikWrndbn5Og.jpg',
      vote_average: 8.9,
      vote_count: 162,
    },
    {
      backdrop_path: '/dwEkNoGFZJWqiwJrnzVfmtmVhfU.jpg',
      first_air_date: '2019-01-11',
      genre_ids: [16, 35, 18],
      id: 84669,
      name: 'The Quintessential Quintuplets',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '五等分の花嫁',
      overview:
        'Fuutarou Uesugi is a poor, antisocial ace student who one day meets the rich transfer student Itsuki Nakano. They argue but when Uesugi realizes he is to be her tutor, he tries to get on better terms. While trying to do so he meets four other girls.',
      popularity: 128.015,
      poster_path: '/mrahUSmFjae8UHtlOcZ58ytmAGu.jpg',
      vote_average: 8.9,
      vote_count: 478,
    },
    {
      backdrop_path: '/mWwWhDiQWONiSS4Go12TTjNw0E5.jpg',
      first_air_date: '2016-10-06',
      genre_ids: [16, 35, 18],
      id: 68129,
      name: 'Yuri!!! on Ice',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: 'ユーリ!!! on ICE',
      overview:
        "Yūri Katsuki carried all of Japan's hopes on his shoulders to win at the Gran Prix Finale ice skating competition, but suffered a crushing defeat. He returns home to Kyushu and half feels like he wants to retire, and half feels like he wants to continue ice skating. Suddenly the five-time consecutive world championship ice skater Victor Nikiforov appears before him with Yuri Plisetsky, a young Russian figure skater who is already defeating his seniors. Victor and both Yuris take up the challenge on an unprecedented Gran Prix series.",
      popularity: 31.56,
      poster_path: '/oKVFf2uNCLMsovWBxAW14MmhHUm.jpg',
      vote_average: 8.9,
      vote_count: 457,
    },
    {
      backdrop_path: '/T2Oi1KTOOVhHygBK99yX4QHZg9.jpg',
      first_air_date: '2021-02-20',
      genre_ids: [10759, 35, 18],
      id: 117376,
      name: 'Vincenzo',
      origin_country: ['KR'],
      original_language: 'ko',
      original_name: '빈센조',
      overview:
        'Vincenzo Cassano is an Italian lawyer and Mafia consigliere who moves back to Korea due to a conflict within his organization. He ends up crossing paths with a sharp-tongued lawyer named Cha-young, and the two join forces in using villainous methods to take down villains who cannot be punished by the law.',
      popularity: 98.715,
      poster_path: '/dvXJgEDQXhL9Ouot2WkBHpQiHGd.jpg',
      vote_average: 8.9,
      vote_count: 433,
    },
    {
      backdrop_path: '/zEQz64k0WD8SLd97MDCgauAsXQn.jpg',
      first_air_date: '2010-04-23',
      genre_ids: [16, 10759, 10762, 10751, 9648],
      id: 32118,
      name: 'Generator Rex',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Generator Rex',
      overview:
        'Generator Rex, an average teenager with the ability to turn his body into amazing machines, helps the secret organization Providence save the world from the nanite threat and dangerous EVO monsters.',
      popularity: 40.749,
      poster_path: '/fL7S22SWWOjJTgHEkk68VZ4Z8RO.jpg',
      vote_average: 8.9,
      vote_count: 250,
    },
    {
      backdrop_path: '/rXXC22YUo31QfOsavy0jUbqdxFc.jpg',
      first_air_date: '2014-12-09',
      genre_ids: [10765, 10759, 16],
      id: 73055,
      name: 'Attack on Titan: No Regrets',
      origin_country: ['JP'],
      original_language: 'ja',
      original_name: '進撃の巨人 悔いなき選択',
      overview:
        "Many years before becoming the famed captain of the Survey Corps, a young Levi struggles to survive in the capital's garbage dump, the Underground. As the boss of his own criminal operation, Levi attempts to get by with meager earnings while aided by fellow criminals, Isabel Magnolia and Farlan Church. With little hope for the future, Levi accepts a deal from the anti-expedition faction leader Nicholas Lobov, who promises the trio citizenship aboveground if they are able to successfully assassinate Erwin Smith, a squad leader of the Survey Corps.",
      popularity: 148.928,
      poster_path: '/xGdz67d5WHIU7kIqVHO2TxIpmhZ.jpg',
      vote_average: 8.9,
      vote_count: 1888,
    },
  ],
  total_pages: 114,
  total_results: 2270,
};

export const Top10TvShowsMock: TvShow[] = TvShowsResultsMock.results.slice(
  0,
  10
);

export const TvShowDetailsMock: TvShowDetails = {
  backdrop_path: null,
  created_by: [],
  episode_run_time: [30],
  first_air_date: '2004-05-10',
  genres: [
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 35,
      name: 'Comedy',
    },
  ],
  homepage: 'https://www.bbc.co.uk/programmes/p011fgk5',
  id: 100,
  in_production: false,
  languages: [],
  last_air_date: '2004-10-19',
  last_episode_to_air: {
    air_date: '2004-10-19',
    episode_number: 3,
    id: 4694,
    name: 'Money',
    overview: 'The animals begin to have problems with money.',
    production_code: '',
    season_number: 1,
    still_path: null,
    vote_average: 0,
    vote_count: 0,
  },
  name: 'I Am Not an Animal',
  next_episode_to_air: null,
  networks: [
    {
      name: 'BBC Two',
      id: 332,
      logo_path: '/7HVPn1p2w1nC5oRKBehXVHpss7e.png',
      origin_country: 'GB',
    },
  ],
  number_of_episodes: 6,
  number_of_seasons: 1,
  origin_country: ['GB'],
  original_language: 'en',
  original_name: 'I Am Not an Animal',
  overview:
    'I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.',
  popularity: 16.402,
  poster_path: '/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg',
  production_companies: [
    {
      id: 72930,
      logo_path: null,
      name: 'Baby Cow Animation',
      origin_country: 'GB',
    },
  ],
  production_countries: [],
  seasons: [
    {
      air_date: null,
      episode_count: 1,
      id: 299,
      name: 'Specials',
      overview: '',
      poster_path: null,
      season_number: 0,
    },
    {
      air_date: '2004-05-10',
      episode_count: 6,
      id: 298,
      name: 'Season 1',
      overview: '',
      poster_path: null,
      season_number: 1,
    },
  ],
  spoken_languages: [],
  status: 'Ended',
  tagline: '',
  type: 'Scripted',
  vote_average: 9.2,
  vote_count: 690,
  videos: {
    results: [
      {
        iso_639_1: 'en',
        iso_3166_1: 'US',
        name: 'I Am Not An Animal trailer (Steve Coogan, 2004)',
        key: 'nj57oWfbILA',
        site: 'YouTube',
        size: 360,
        type: 'Trailer',
        official: false,
        published_at: '2017-07-06T22:08:12.000Z',
        id: '5cb8bea9c3a3686af286424b',
      },
    ],
  },
};

export const TvShowCreditsMock: Credits = {
  cast: [
    {
      adult: false,
      gender: 1,
      id: 1836,
      known_for_department: 'Acting',
      name: 'Julia Davis',
      original_name: 'Julia Davis',
      popularity: 7.737,
      profile_path: '/wsUNCSKoNQTgSdlr9FIeIR6hRAd.jpg',
      character: 'Claire the Rat (voice)',
      credit_id: '525338ee19c2957940059508',
      order: 0,
    },
    {
      adult: false,
      gender: 2,
      id: 39185,
      known_for_department: 'Acting',
      name: 'Kevin Eldon',
      original_name: 'Kevin Eldon',
      popularity: 6.867,
      profile_path: '/5Ws7v11Y6N4bLPSed4HffjCajaX.jpg',
      character: 'Hugh the Monkey (voice)',
      credit_id: '525338ee19c2957940059524',
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 11108,
      known_for_department: 'Acting',
      name: 'Simon Pegg',
      original_name: 'Simon Pegg',
      popularity: 22.549,
      profile_path: '/nOWKXxgADG98RjKyfQ7oSDfns6J.jpg',
      character: 'Kieron the Cat (voice)',
      credit_id: '525338ee19c295794005953a',
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 4581,
      known_for_department: 'Acting',
      name: 'Steve Coogan',
      original_name: 'Steve Coogan',
      popularity: 8.893,
      profile_path: '/tT7OXc2qA6hlREHXdwGLp0XihzA.jpg',
      character: 'Mark the Bird (voice)',
      credit_id: '525338ee19c2957940059550',
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 93713,
      known_for_department: 'Acting',
      name: 'Amelia Bullmore',
      original_name: 'Amelia Bullmore',
      popularity: 6.199,
      profile_path: '/qsvkxSBAxj1O1pEXUFIyh85YMk9.jpg',
      character: 'Winona the Dog (voice)',
      credit_id: '525338ee19c295794005956c',
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 940,
      known_for_department: 'Acting',
      name: 'John Shrapnel',
      original_name: 'John Shrapnel',
      popularity: 2.665,
      profile_path: '/A4Wmltbkz3sz79GcBkLeTqwfkvE.jpg',
      character: 'Narrator',
      credit_id: '525338ef19c29579400595a0',
      order: 5,
    },
    {
      adult: false,
      gender: 0,
      id: 1213132,
      known_for_department: 'Writing',
      name: 'Arthur Mathews',
      original_name: 'Arthur Mathews',
      popularity: 1.008,
      profile_path: null,
      character: 'Niall the Rabbit (voice)',
      credit_id: '525338ef19c29579400595b8',
      order: 6,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 4581,
      known_for_department: 'Acting',
      name: 'Steve Coogan',
      original_name: 'Steve Coogan',
      popularity: 8.893,
      profile_path: '/tT7OXc2qA6hlREHXdwGLp0XihzA.jpg',
      credit_id: '525338ef19c29579400595d2',
      department: 'Production',
      job: 'Producer',
    },
  ],
  id: 100,
};
