import { Credits } from '@core/models/credits';
import { Movie } from '@core/models/movie';
import { MovieDetails } from '@core/models/movie-details';
import { TmdbApiGetResponse } from '@core/models/tmdb-api-get-response';

export const MovieResultsMock: TmdbApiGetResponse<Movie> = {
  page: 1,
  results: [
    {
      poster_path: '/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg',
      adult: false,
      overview:
        'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
      release_date: '1994-09-10',
      genre_ids: [18, 80],
      id: 278,
      original_title: 'The Shawshank Redemption',
      original_language: 'en',
      title: 'The Shawshank Redemption',
      backdrop_path: '/xBKGJQsAIeweesB79KC89FpBrVr.jpg',
      popularity: 6.741296,
      vote_count: 5238,
      video: false,
      vote_average: 8.32,
    },
    {
      poster_path: '/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg',
      adult: false,
      overview:
        'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
      release_date: '2014-10-10',
      genre_ids: [18, 10402],
      id: 244786,
      original_title: 'Whiplash',
      original_language: 'en',
      title: 'Whiplash',
      backdrop_path: '/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg',
      popularity: 10.776056,
      vote_count: 2059,
      video: false,
      vote_average: 8.29,
    },
    {
      poster_path: '/d4KNaTrltq6bpkFS01pYtyXa09m.jpg',
      adult: false,
      overview:
        'The story spans the years from 1945 to 1955 and chronicles the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: '1972-03-15',
      genre_ids: [18, 80],
      id: 238,
      original_title: 'The Godfather',
      original_language: 'en',
      title: 'The Godfather',
      backdrop_path: '/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg',
      popularity: 4.554654,
      vote_count: 3570,
      video: false,
      vote_average: 8.26,
    },
    {
      poster_path: '/ynXoOxmDHNQ4UAy0oU6avW71HVW.jpg',
      adult: false,
      overview:
        'Spirited Away is an Oscar winning Japanese animated film about a ten year old girl who wanders away from her parents along a path that leads to a world ruled by strange and unusual monster-like animals. Her parents have been changed into pigs along with others inside a bathhouse full of these creatures. Will she ever see the world how it once was?',
      release_date: '2001-07-20',
      genre_ids: [14, 12, 16, 10751],
      id: 129,
      original_title: '千と千尋の神隠し',
      original_language: 'ja',
      title: 'Spirited Away',
      backdrop_path: '/djgM2d3e42p9GFQObg6lwK2SVw2.jpg',
      popularity: 6.886678,
      vote_count: 2000,
      video: false,
      vote_average: 8.15,
    },
    {
      poster_path: '/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg',
      adult: false,
      overview:
        'Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
      release_date: '2014-11-05',
      genre_ids: [12, 18, 878],
      id: 157336,
      original_title: 'Interstellar',
      original_language: 'en',
      title: 'Interstellar',
      backdrop_path: '/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
      popularity: 12.481061,
      vote_count: 5600,
      video: false,
      vote_average: 8.12,
    },
    {
      poster_path: '/tHbMIIF51rguMNSastqoQwR0sBs.jpg',
      adult: false,
      overview:
        'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba',
      release_date: '1974-12-20',
      genre_ids: [18, 80],
      id: 240,
      original_title: 'The Godfather: Part II',
      original_language: 'en',
      title: 'The Godfather: Part II',
      backdrop_path: '/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg',
      popularity: 4.003715,
      vote_count: 1894,
      video: false,
      vote_average: 8.1,
    },
    {
      poster_path: '/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg',
      adult: false,
      overview:
        'A true story of two men who should never have met - a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects.',
      release_date: '2011-11-02',
      genre_ids: [18, 35],
      id: 77338,
      original_title: 'Intouchables',
      original_language: 'fr',
      title: 'The Intouchables',
      backdrop_path: '/ihWaJZCUIon2dXcosjQG2JHJAPN.jpg',
      popularity: 3.698279,
      vote_count: 2740,
      video: false,
      vote_average: 8.1,
    },
    {
      poster_path: '/bwVhmPpydv8P7mWfrmL3XVw0MV5.jpg',
      adult: false,
      overview:
        'In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.',
      release_date: '1988-04-16',
      genre_ids: [16, 18, 10751, 10752],
      id: 12477,
      original_title: '火垂るの墓',
      original_language: 'ja',
      title: 'Grave of the Fireflies',
      backdrop_path: '/fCUIuG7y4YKC3hofZ8wsj7zhCpR.jpg',
      popularity: 1.001401,
      vote_count: 430,
      video: false,
      vote_average: 8.07,
    },
    {
      poster_path: '/yPisjyLweCl1tbgwgtzBCNCBle.jpg',
      adult: false,
      overview:
        'Told from the perspective of businessman Oskar Schindler who saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory. Schindler’s List is based on a true story, illustrated in black and white and controversially filmed in many original locations.',
      release_date: '1993-11-29',
      genre_ids: [18, 36, 10752],
      id: 424,
      original_title: "Schindler's List",
      original_language: 'en',
      title: "Schindler's List",
      backdrop_path: '/rIpSszng8P0DL0TimSzZbpfnvh1.jpg',
      popularity: 5.372319,
      vote_count: 2308,
      video: false,
      vote_average: 8.07,
    },
    {
      poster_path: '/eqFckcHuFCT1FrzLOAvXBb4jHwq.jpg',
      adult: false,
      overview:
        'Jack is a young boy of 5 years old who has lived all his life in one room. He believes everything within it are the only real things in the world. But what will happen when his Ma suddenly tells him that there are other things outside of Room?',
      release_date: '2015-10-16',
      genre_ids: [18, 53],
      id: 264644,
      original_title: 'Room',
      original_language: 'en',
      title: 'Room',
      backdrop_path: '/tBhp8MGaiL3BXpPCSl5xY397sGH.jpg',
      popularity: 5.593128,
      vote_count: 1179,
      video: false,
      vote_average: 8.06,
    },
    {
      poster_path: '/f7DImXDebOs148U4uPjI61iDvaK.jpg',
      adult: false,
      overview:
        'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
      release_date: '1997-12-20',
      genre_ids: [35, 18],
      id: 637,
      original_title: 'La vita è bella',
      original_language: 'it',
      title: 'Life Is Beautiful',
      backdrop_path: '/bORe0eI72D874TMawOOFvqWS6Xe.jpg',
      popularity: 5.385594,
      vote_count: 1593,
      video: false,
      vote_average: 8.06,
    },
    {
      poster_path: '/s0C78plmx3dFcO3WMnoXCz56FiN.jpg',
      adult: false,
      overview:
        'A boy growing up in Dublin during the 1980s escapes his strained family life by starting a band to impress the mysterious girl he likes.',
      release_date: '2016-04-15',
      genre_ids: [10749, 18, 10402],
      id: 369557,
      original_title: 'Sing Street',
      original_language: 'en',
      title: 'Sing Street',
      backdrop_path: '/9j4UaRypr19wz0BOofwvkPRm1Se.jpg',
      popularity: 3.343073,
      vote_count: 61,
      video: false,
      vote_average: 8.06,
    },
    {
      poster_path: '/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg',
      adult: false,
      overview:
        'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      release_date: '2008-07-16',
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_title: 'The Dark Knight',
      original_language: 'en',
      title: 'The Dark Knight',
      backdrop_path: '/nnMC0BM6XbjIIrT4miYmMtPGcQV.jpg',
      popularity: 8.090715,
      vote_count: 7744,
      video: false,
      vote_average: 8.06,
    },
    {
      poster_path: '/811DjJTon9gD6hZ8nCjSitaIXFQ.jpg',
      adult: false,
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      release_date: '1999-10-14',
      genre_ids: [18],
      id: 550,
      original_title: 'Fight Club',
      original_language: 'en',
      title: 'Fight Club',
      backdrop_path: '/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg',
      popularity: 6.590102,
      vote_count: 5221,
      video: false,
      vote_average: 8.05,
    },
    {
      poster_path: '/dM2w364MScsjFf8pfMbaWUcWrR.jpg',
      adult: false,
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      release_date: '1994-10-14',
      genre_ids: [53, 80],
      id: 680,
      original_title: 'Pulp Fiction',
      original_language: 'en',
      title: 'Pulp Fiction',
      backdrop_path: '/mte63qJaVnoxkkXbHkdFujBnBgd.jpg',
      popularity: 7.760216,
      vote_count: 4722,
      video: false,
      vote_average: 8.04,
    },
    {
      poster_path: '/gzlJkVfWV5VEG5xK25cvFGJgkDz.jpg',
      adult: false,
      overview:
        'Ashitaka, a prince of the disappearing Ainu tribe, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.',
      release_date: '1997-07-12',
      genre_ids: [12, 14, 16],
      id: 128,
      original_title: 'もののけ姫',
      original_language: 'ja',
      title: 'Princess Mononoke',
      backdrop_path: '/dB2rATwfCbsPGfRLIoluBnKdVHb.jpg',
      popularity: 4.672361,
      vote_count: 954,
      video: false,
      vote_average: 8.04,
    },
    {
      poster_path: '/3TpMBcAYH4cxCw5WoRacWodMTCG.jpg',
      adult: false,
      overview:
        'An urban office worker finds that paper airplanes are instrumental in meeting a girl in ways he never expected.',
      release_date: '2012-11-02',
      genre_ids: [16, 10751, 10749],
      id: 140420,
      original_title: 'Paperman',
      original_language: 'en',
      title: 'Paperman',
      backdrop_path: '/cqn1ynw78Wan37jzs1Ckm7va97G.jpg',
      popularity: 2.907096,
      vote_count: 452,
      video: false,
      vote_average: 8.03,
    },
    {
      poster_path: '/pwpGfTImTGifEGgLb3s6LRPd4I6.jpg',
      adult: false,
      overview:
        'Henry Hill is a small time gangster, who takes part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who have set their sights a bit higher. His two partners kill off everyone else involved in the robbery, and slowly start to climb up through the hierarchy of the Mob. Henry, however, is badly affected by his partners success, but will he stoop low enough to bring about the downfall of Jimmy and Tommy?',
      release_date: '1990-09-12',
      genre_ids: [18, 80],
      id: 769,
      original_title: 'Goodfellas',
      original_language: 'en',
      title: 'Goodfellas',
      backdrop_path: '/xDEOxA01480uLTWuvQCw61VmDBt.jpg',
      popularity: 3.783589,
      vote_count: 1528,
      video: false,
      vote_average: 8.02,
    },
    {
      poster_path: '/z4ROnCrL77ZMzT0MsNXY5j25wS2.jpg',
      adult: false,
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. 'Forrest Gump' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.",
      release_date: '1994-07-06',
      genre_ids: [35, 18, 10749],
      id: 13,
      original_title: 'Forrest Gump',
      original_language: 'en',
      title: 'Forrest Gump',
      backdrop_path: '/ctOEhQiFIHWkiaYp7b0ibSTe5IL.jpg',
      popularity: 6.224491,
      vote_count: 4279,
      video: false,
      vote_average: 8.02,
    },
    {
      poster_path: '/5hqbJSmtAimbaP3XcYshCixuUtk.jpg',
      adult: false,
      overview:
        "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.",
      release_date: '1954-04-26',
      genre_ids: [28, 18],
      id: 346,
      original_title: '七人の侍',
      original_language: 'ja',
      title: 'Seven Samurai',
      backdrop_path: '/61vLiK96sbXeHpQiMxI4CuqBA3z.jpg',
      popularity: 2.93856,
      vote_count: 436,
      video: false,
      vote_average: 8.02,
    },
  ],
  total_results: 5206,
  total_pages: 261,
};

export const Top10RatedMoviesMock: Movie[] = MovieResultsMock.results.slice(
  0,
  10
);

export const MovieDetailsMock: MovieDetails = {
  adult: false,
  backdrop_path: '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
  belongs_to_collection: {
    id: 230,
    name: 'The Godfather Collection',
    poster_path: '/9Baumh5J9N1nJUYzNkm0xsgjpwY.jpg',
    backdrop_path: '/3WZTxpgscsmoUk81TuECXdFOD0R.jpg',
  },
  budget: 6000000,
  genres: [
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 80,
      name: 'Crime',
    },
  ],
  homepage: 'http://www.thegodfather.com/',
  id: 238,
  imdb_id: 'tt0068646',
  original_language: 'en',
  original_title: 'The Godfather',
  overview:
    'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  popularity: 80.602,
  poster_path: '/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg',
  production_companies: [
    {
      id: 4,
      logo_path: '/fycMZt242LVjagMByZOLUGbCvv3.png',
      name: 'Paramount',
      origin_country: 'US',
    },
    {
      id: 10211,
      logo_path: null,
      name: 'Alfran Productions',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '1972-03-14',
  revenue: 245066411,
  runtime: 175,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
    {
      english_name: 'Italian',
      iso_639_1: 'it',
      name: 'Italiano',
    },
    {
      english_name: 'Latin',
      iso_639_1: 'la',
      name: 'Latin',
    },
  ],
  status: 'Released',
  tagline: "An offer you can't refuse.",
  title: 'The Godfather',
  video: false,
  vote_average: 8.7,
  vote_count: 15407,
  videos: {
    results: [
      {
        iso_639_1: 'en',
        iso_3166_1: 'US',
        name: '50th Anniversary Trailer',
        key: 'Ew9ngL1GZvs',
        site: 'YouTube',
        size: 2160,
        type: 'Trailer',
        official: true,
        published_at: '2022-01-13T13:59:54.000Z',
        id: '61e4e0704f58010019f1fc53',
      },
      {
        iso_639_1: 'en',
        iso_3166_1: 'US',
        name: "Offer He Can't Refuse",
        key: 'fBNpSRtfIUA',
        published_at: '2016-03-06T22:19:42.000Z',
        site: 'YouTube',
        size: 1080,
        type: 'Clip',
        official: true,
        id: '592199669251414ab10568ec',
      },
    ],
  },
};

export const MovieCreditsMock: Credits = {
  id: 238,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 3084,
      known_for_department: 'Acting',
      name: 'Marlon Brando',
      original_name: 'Marlon Brando',
      popularity: 15.987,
      profile_path: '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg',
      cast_id: 5,
      character: 'Don Vito Corleone',
      credit_id: '52fe422bc3a36847f8009357',
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1158,
      known_for_department: 'Acting',
      name: 'Al Pacino',
      original_name: 'Al Pacino',
      popularity: 24.327,
      profile_path: '/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg',
      cast_id: 6,
      character: 'Don Michael Corleone',
      credit_id: '52fe422bc3a36847f800935b',
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 3085,
      known_for_department: 'Acting',
      name: 'James Caan',
      original_name: 'James Caan',
      popularity: 25.238,
      profile_path: '/bGyOCCOIgcIyKjOGLoXoyp0XWHf.jpg',
      cast_id: 7,
      character: 'Santino "Sonny" Corleone',
      credit_id: '52fe422bc3a36847f800935f',
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 3087,
      known_for_department: 'Acting',
      name: 'Robert Duvall',
      original_name: 'Robert Duvall',
      popularity: 21.514,
      profile_path: '/ybMmK25h4IVtfE7qrnlVp47RQlh.jpg',
      cast_id: 9,
      character: 'Tom Hagen',
      credit_id: '52fe422bc3a36847f8009367',
      order: 4,
    },
    {
      adult: false,
      gender: 0,
      id: 3086,
      known_for_department: 'Acting',
      name: 'Richard S. Castellano',
      original_name: 'Richard S. Castellano',
      popularity: 9.56,
      profile_path: '/1vr75BdHWret81vuSJ3ugiCBkxw.jpg',
      cast_id: 8,
      character: 'Pete Clemenza',
      credit_id: '52fe422bc3a36847f8009363',
      order: 5,
    },
    {
      adult: false,
      gender: 1,
      id: 3092,
      known_for_department: 'Acting',
      name: 'Diane Keaton',
      original_name: 'Diane Keaton',
      popularity: 19.403,
      profile_path: '/7gEdH5vGwpUpogscTb2JivnoRBb.jpg',
      cast_id: 13,
      character: 'Kay Adams',
      credit_id: '52fe422bc3a36847f8009377',
      order: 6,
    },
    {
      adult: false,
      gender: 1,
      id: 3094,
      known_for_department: 'Acting',
      name: 'Talia Shire',
      original_name: 'Talia Shire',
      popularity: 14.908,
      profile_path: '/xvJ47wKL5zpwFXFFNZQmFmf7i9F.jpg',
      cast_id: 15,
      character: 'Constanzia "Connie" Corleone-Rizzi',
      credit_id: '52fe422bc3a36847f800937f',
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 3095,
      known_for_department: 'Acting',
      name: 'Gianni Russo',
      original_name: 'Gianni Russo',
      popularity: 6.917,
      profile_path: '/5fjg2WPvuk1NvUpLyQ7aMJqOqy.jpg',
      cast_id: 16,
      character: 'Carlo Rizzi',
      credit_id: '52fe422bc3a36847f8009383',
      order: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 3088,
      known_for_department: 'Acting',
      name: 'Sterling Hayden',
      original_name: 'Sterling Hayden',
      popularity: 7.118,
      profile_path: '/bMpJtVo741q83q3qLtraqYO4cVh.jpg',
      cast_id: 10,
      character: 'Capt. Mark McCluskey',
      credit_id: '52fe422bc3a36847f800936b',
      order: 9,
    },
    {
      adult: false,
      gender: 2,
      id: 3091,
      known_for_department: 'Acting',
      name: 'Al Lettieri',
      original_name: 'Al Lettieri',
      popularity: 7.992,
      profile_path: '/fE5mEWPkkVJlCji0EoKht8PYw89.jpg',
      cast_id: 12,
      character: 'Virgil "The Turk" Sollozzo',
      credit_id: '52fe422bc3a36847f8009373',
      order: 10,
    },
    {
      adult: false,
      gender: 2,
      id: 3093,
      known_for_department: 'Acting',
      name: 'Abe Vigoda',
      original_name: 'Abe Vigoda',
      popularity: 5.5,
      profile_path: '/luWKPNb58IgJ2ovrtgPAzHGLLYL.jpg',
      cast_id: 14,
      character: 'Salvatore "Sal" Tessio',
      credit_id: '52fe422bc3a36847f800937b',
      order: 11,
    },
    {
      adult: false,
      gender: 2,
      id: 3096,
      known_for_department: 'Acting',
      name: 'John Cazale',
      original_name: 'John Cazale',
      popularity: 13.007,
      profile_path: '/41wXX1FBalyIuf5eaA4S43Y8IfZ.jpg',
      cast_id: 17,
      character: 'Frederico "Fredo" Corleone',
      credit_id: '52fe422bc3a36847f8009387',
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 3090,
      known_for_department: 'Acting',
      name: 'Richard Conte',
      original_name: 'Richard Conte',
      popularity: 4.283,
      profile_path: '/pTTzNets0bgWAqx18D7by0hWUea.jpg',
      cast_id: 11,
      character: 'Don Emilio Barzini',
      credit_id: '52fe422bc3a36847f800936f',
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 3142,
      known_for_department: 'Acting',
      name: 'John Marley',
      original_name: 'John Marley',
      popularity: 5.27,
      profile_path: null,
      cast_id: 33,
      character: 'Jack Woltz',
      credit_id: '52fe422bc3a36847f800938b',
      order: 14,
    },
    {
      adult: false,
      gender: 2,
      id: 3143,
      known_for_department: 'Acting',
      name: 'Rudy Bond',
      original_name: 'Rudy Bond',
      popularity: 2.308,
      profile_path: '/kP77m6ot9dfOR2V3ykbyOAx2diK.jpg',
      cast_id: 34,
      character: 'Carmine Cuneo',
      credit_id: '52fe422bc3a36847f800938f',
      order: 15,
    },
    {
      adult: false,
      gender: 2,
      id: 3144,
      known_for_department: 'Acting',
      name: 'Al Martino',
      original_name: 'Al Martino',
      popularity: 0.771,
      profile_path: '/9luOyyiqWFNQgSOSStH66LTWZ3p.jpg',
      cast_id: 35,
      character: 'Johnny Fontane',
      credit_id: '52fe422bc3a36847f8009393',
      order: 16,
    },
    {
      adult: false,
      gender: 1,
      id: 933716,
      known_for_department: 'Acting',
      name: 'Morgana King',
      original_name: 'Morgana King',
      popularity: 3.392,
      profile_path: '/zPsFAqH4NXD7rMWl2Kj3rEyGrKj.jpg',
      cast_id: 42,
      character: 'Carmela "Mama" Corleone',
      credit_id: '52fe422bc3a36847f80093a7',
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 106811,
      known_for_department: 'Acting',
      name: 'Lenny Montana',
      original_name: 'Lenny Montana',
      popularity: 2.862,
      profile_path: '/3R52Zh3MBCaSPqmcyWcD1Y0N4wo.jpg',
      cast_id: 45,
      character: 'Luca Brasi',
      credit_id: '52fe422bc3a36847f80093b3',
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 99724,
      known_for_department: 'Acting',
      name: 'John Martino',
      original_name: 'John Martino',
      popularity: 0.828,
      profile_path: '/3c8BOgJ8UdHi5x5BS3lYnFngxB5.jpg',
      cast_id: 47,
      character: 'Paulie Gatto',
      credit_id: '52fe422bc3a36847f80093bb',
      order: 19,
    },
    {
      adult: false,
      gender: 2,
      id: 20752,
      known_for_department: 'Acting',
      name: 'Alex Rocco',
      original_name: 'Alex Rocco',
      popularity: 7.602,
      profile_path: '/uAG4qvYhYHuCyyXGm3lqC4o6ujc.jpg',
      cast_id: 41,
      character: 'Moe Greene',
      credit_id: '52fe422bc3a36847f80093a3',
      order: 20,
    },
    {
      adult: false,
      gender: 0,
      id: 1195877,
      known_for_department: 'Acting',
      name: 'Salvatore Corsitto',
      original_name: 'Salvatore Corsitto',
      popularity: 1.243,
      profile_path: '/79OfgwtdP5qsR1UX6ERkrdmRT8c.jpg',
      cast_id: 46,
      character: 'Amerigo Bonasera',
      credit_id: '52fe422bc3a36847f80093b7',
      order: 21,
    },
    {
      adult: false,
      gender: 2,
      id: 3414,
      known_for_department: 'Acting',
      name: 'Tony Giorgio',
      original_name: 'Tony Giorgio',
      popularity: 4.315,
      profile_path: '/1uhgwgjoX7WaakEOBmtBRJKtgEB.jpg',
      cast_id: 38,
      character: 'Bruno Tattaglia',
      credit_id: '52fe422bc3a36847f800939f',
      order: 22,
    },
    {
      adult: false,
      gender: 2,
      id: 3413,
      known_for_department: 'Acting',
      name: 'Victor Rendina',
      original_name: 'Victor Rendina',
      popularity: 3.953,
      profile_path: '/vuNdsjDpgom80WBdB2WBTWuEIuM.jpg',
      cast_id: 37,
      character: 'Philip Tattaglia',
      credit_id: '52fe422bc3a36847f800939b',
      order: 23,
    },
    {
      adult: false,
      gender: 1,
      id: 3145,
      known_for_department: 'Acting',
      name: 'Simonetta Stefanelli',
      original_name: 'Simonetta Stefanelli',
      popularity: 12.64,
      profile_path: '/sVDrhgxuE6SHnj7q07OG6ywPUYR.jpg',
      cast_id: 36,
      character: 'Apollonia Vitelli-Corleone',
      credit_id: '52fe422bc3a36847f8009397',
      order: 24,
    },
    {
      adult: false,
      gender: 2,
      id: 119431,
      known_for_department: 'Acting',
      name: 'Saro Urzì',
      original_name: 'Saro Urzì',
      popularity: 5.302,
      profile_path: '/nPJytCpcNdG5ssPoKeEvxM6xifx.jpg',
      cast_id: 48,
      character: 'Mr. Vitelli',
      credit_id: '52fe422bc3a36847f80093bf',
      order: 25,
    },
    {
      adult: false,
      gender: 1,
      id: 1769,
      known_for_department: 'Directing',
      name: 'Sofia Coppola',
      original_name: 'Sofia Coppola',
      popularity: 5.935,
      profile_path: '/dzHC2LxmarkBxWLhjp2DRa5oCev.jpg',
      cast_id: 43,
      character: 'Michael Francis Rizzi',
      credit_id: '52fe422bc3a36847f80093ab',
      order: 26,
    },
    {
      adult: false,
      gender: 2,
      id: 20973,
      known_for_department: 'Acting',
      name: 'Louis Guss',
      original_name: 'Louis Guss',
      popularity: 4.158,
      profile_path: '/hz5Akuh4QcqitlifYwDiZ9ut6Tr.jpg',
      cast_id: 44,
      character: 'Don Zaluchi',
      credit_id: '52fe422bc3a36847f80093af',
      order: 27,
    },
    {
      adult: false,
      gender: 0,
      id: 138211,
      known_for_department: 'Acting',
      name: 'Gabriele Torrei',
      original_name: 'Gabriele Torrei',
      popularity: 4.846,
      profile_path: '/x3KeYWTWX5SqZ3NuQGiWiadO4DI.jpg',
      cast_id: 49,
      character: 'Enzo the Baker (uncredited)',
      credit_id: '52fe422bc3a36847f80093c3',
      order: 28,
    },
    {
      adult: false,
      gender: 2,
      id: 55672,
      known_for_department: 'Acting',
      name: 'Tony King',
      original_name: 'Tony King',
      popularity: 1.189,
      profile_path: '/hOVVHEyc6euuuRhCLo6Q5YE4lLz.jpg',
      cast_id: 69,
      character: 'Tony the Stablehand (uncredited)',
      credit_id: '54de315fc3a3685446001351',
      order: 29,
    },
    {
      adult: false,
      gender: 2,
      id: 3174,
      known_for_department: 'Acting',
      name: 'Richard Bright',
      original_name: 'Richard Bright',
      popularity: 5.662,
      profile_path: '/potMaJ2u5PRjXZb7qF9lSW1ldNZ.jpg',
      cast_id: 70,
      character: 'Neri',
      credit_id: '55be4cdbc3a3683921003065',
      order: 30,
    },
    {
      adult: false,
      gender: 2,
      id: 82779,
      known_for_department: 'Acting',
      name: 'Vito Scotti',
      original_name: 'Vito Scotti',
      popularity: 2.461,
      profile_path: '/zDGtXkASxpo3DzMNz6OI3NOp9v0.jpg',
      cast_id: 71,
      character: 'Nazorine',
      credit_id: '55be4cff9251413e49004a59',
      order: 31,
    },
    {
      adult: false,
      gender: 1,
      id: 982089,
      known_for_department: 'Acting',
      name: 'Tere Livrano',
      original_name: 'Tere Livrano',
      popularity: 2.801,
      profile_path: '/eBoC3425jmwRlsT2W8qUDsNwVXB.jpg',
      cast_id: 72,
      character: 'Theresa Hagen',
      credit_id: '55be4d40c3a368392100306d',
      order: 32,
    },
    {
      adult: false,
      gender: 1,
      id: 160728,
      known_for_department: 'Acting',
      name: 'Julie Gregg',
      original_name: 'Julie Gregg',
      popularity: 3.908,
      profile_path: '/8Kx71BnZNtpzb86jH7fcArWhJBh.jpg',
      cast_id: 77,
      character: 'Sandrinella "Sandra" Corleone',
      credit_id: '55ee4ac0c3a3686f170063c4',
      order: 33,
    },
    {
      adult: false,
      gender: 2,
      id: 27647,
      known_for_department: 'Acting',
      name: 'Angelo Infanti',
      original_name: 'Angelo Infanti',
      popularity: 4.094,
      profile_path: '/dkRVpiDj9YyiuM15XZKT11zZBIR.jpg',
      cast_id: 74,
      character: 'Fabrizio',
      credit_id: '55be4dffc3a368652600471c',
      order: 34,
    },
    {
      adult: false,
      gender: 2,
      id: 24604,
      known_for_department: 'Acting',
      name: 'Corrado Gaipa',
      original_name: 'Corrado Gaipa',
      popularity: 4.243,
      profile_path: '/7vR2BOdVw9FwJKjgpcisjKEytnL.jpg',
      cast_id: 75,
      character: 'Don Tommasino',
      credit_id: '55be4e2fc3a3686534005572',
      order: 35,
    },
    {
      adult: false,
      gender: 2,
      id: 44860,
      known_for_department: 'Acting',
      name: 'Franco Citti',
      original_name: 'Franco Citti',
      popularity: 4.927,
      profile_path: '/mttQPjOHaql4RKsfYriUA7HuROE.jpg',
      cast_id: 76,
      character: 'Calò',
      credit_id: '55be4e5bc3a3683921003083',
      order: 36,
    },
    {
      adult: false,
      gender: 0,
      id: 178006,
      known_for_department: 'Acting',
      name: 'Max Brandt',
      original_name: 'Max Brandt',
      popularity: 0.84,
      profile_path: null,
      cast_id: 78,
      character: 'Extra in Furniture-Moving Scene (uncredited)',
      credit_id: '55f1b3c992514167010020a7',
      order: 37,
    },
    {
      adult: false,
      gender: 2,
      id: 2872,
      known_for_department: 'Sound',
      name: 'Carmine Coppola',
      original_name: 'Carmine Coppola',
      popularity: 1.913,
      profile_path: null,
      cast_id: 79,
      character: 'Piano Player in Montage (uncredited)',
      credit_id: '55f1b3ffc3a368230a00239f',
      order: 38,
    },
    {
      adult: false,
      gender: 2,
      id: 38803,
      known_for_department: 'Writing',
      name: 'Roman Coppola',
      original_name: 'Roman Coppola',
      popularity: 3.93,
      profile_path: '/rKamKkx78qjZTfvqi2OWCo5p6x5.jpg',
      cast_id: 80,
      character: 'Boy on Street Who Attended Funeral (uncredited)',
      credit_id: '55f1b452c3a36822f5002395',
      order: 39,
    },
    {
      adult: false,
      gender: 0,
      id: 1209294,
      known_for_department: 'Acting',
      name: 'Don Costello',
      original_name: 'Don Costello',
      popularity: 0.6,
      profile_path: null,
      cast_id: 81,
      character: 'Don Victor Stracci (uncredited)',
      credit_id: '55f1b4bac3a3682303002284',
      order: 40,
    },
    {
      adult: false,
      gender: 2,
      id: 1394703,
      known_for_department: 'Acting',
      name: 'Robert Dahdah',
      original_name: 'Robert Dahdah',
      popularity: 0.6,
      profile_path: null,
      cast_id: 82,
      character: 'Crowd (uncredited)',
      credit_id: '55f1b4de925141670d002392',
      order: 41,
    },
    {
      adult: false,
      gender: 2,
      id: 2870,
      known_for_department: 'Production',
      name: 'Gray Frederickson',
      original_name: 'Gray Frederickson',
      popularity: 0.6,
      profile_path: null,
      cast_id: 83,
      character: "Cowboy on the Set at Woltz's Studio (uncredited)",
      credit_id: '55f1b507925141670d00239a',
      order: 42,
    },
    {
      adult: false,
      gender: 2,
      id: 160621,
      known_for_department: 'Acting',
      name: 'Ron Gilbert',
      original_name: 'Ron Gilbert',
      popularity: 1.646,
      profile_path: '/qrY6w2k0YpuMB2yTCOv6cxeQtmw.jpg',
      cast_id: 84,
      character: 'Usher in Bridal Party (uncredited)',
      credit_id: '55f1b52f9251416711002211',
      order: 43,
    },
    {
      adult: false,
      gender: 2,
      id: 1233541,
      known_for_department: 'Acting',
      name: 'Sonny Grosso',
      original_name: 'Sonny Grosso',
      popularity: 0.84,
      profile_path: null,
      cast_id: 87,
      character: 'Cop Outside Hospital (uncredited)',
      credit_id: '55f1b5bb925141670100210a',
      order: 44,
    },
    {
      adult: false,
      gender: 2,
      id: 1503036,
      known_for_department: 'Acting',
      name: 'Joe Lo Grippo',
      original_name: 'Joe Lo Grippo',
      popularity: 3.248,
      profile_path: null,
      cast_id: 86,
      character: "Sonny's Bodyguard (uncredited)",
      credit_id: '55f1b59dc3a3683bec00231e',
      order: 45,
    },
    {
      adult: false,
      gender: 2,
      id: 1068099,
      known_for_department: 'Acting',
      name: 'Randy Jurgensen',
      original_name: 'Randy Jurgensen',
      popularity: 1.27,
      profile_path: '/xRoN79wRLndTMCJoaBSsdjQVIzI.jpg',
      cast_id: 89,
      character: "Sonny's Killer #1 (uncredited)",
      credit_id: '55f1b61ec3a3683bec002335',
      order: 46,
    },
    {
      adult: false,
      gender: 2,
      id: 61241,
      known_for_department: 'Acting',
      name: 'Tony Lip',
      original_name: 'Tony Lip',
      popularity: 3.371,
      profile_path: '/6xz6XmjgiCCOm067OzWYziD4Mxa.jpg',
      cast_id: 90,
      character: 'Wedding Guest (uncredited)',
      credit_id: '55f1b685c3a36823070023b6',
      order: 47,
    },
    {
      adult: false,
      gender: 2,
      id: 106187,
      known_for_department: 'Acting',
      name: 'Lou Martini Jr.',
      original_name: 'Lou Martini Jr.',
      popularity: 3.383,
      profile_path: null,
      cast_id: 91,
      character: 'Boy at Wedding (uncredited)',
      credit_id: '55f1b6c39251416701002141',
      order: 48,
    },
    {
      adult: false,
      gender: 2,
      id: 100503,
      known_for_department: 'Acting',
      name: 'Raymond Martino',
      original_name: 'Raymond Martino',
      popularity: 1.31,
      profile_path: null,
      cast_id: 92,
      character: 'Corleone Family Member (uncredited)',
      credit_id: '55f1b6e59251416711002257',
      order: 49,
    },
    {
      adult: false,
      gender: 2,
      id: 1503035,
      known_for_department: 'Acting',
      name: 'Joseph Medaglia',
      original_name: 'Joseph Medaglia',
      popularity: 1.96,
      profile_path: null,
      cast_id: 93,
      character: 'Priest at Baptism (uncredited)',
      credit_id: '55f1b73dc3a3685eb80005f7',
      order: 50,
    },
    {
      adult: false,
      gender: 0,
      id: 1290895,
      known_for_department: 'Acting',
      name: 'Rick Petrucelli',
      original_name: 'Rick Petrucelli',
      popularity: 1.166,
      profile_path: null,
      cast_id: 94,
      character: 'Man in Passenger Seat (uncredited)',
      credit_id: '55f1b769925141671400218e',
      order: 51,
    },
    {
      adult: false,
      gender: 0,
      id: 1237372,
      known_for_department: 'Acting',
      name: 'Sal Richards',
      original_name: 'Sal Richards',
      popularity: 1.604,
      profile_path: '/gZSiZOtBVv1U4hqjlKkPr2p5rCP.jpg',
      cast_id: 95,
      character: 'Drunk (uncredited)',
      credit_id: '55f1b7c29251410d6d000acb',
      order: 52,
    },
    {
      adult: false,
      gender: 2,
      id: 1213795,
      known_for_department: 'Acting',
      name: 'Tom Rosqui',
      original_name: 'Tom Rosqui',
      popularity: 0.652,
      profile_path: null,
      cast_id: 96,
      character: 'Rocco Lampone (uncredited)',
      credit_id: '55f1b7e2925141670d00243a',
      order: 53,
    },
    {
      adult: false,
      gender: 2,
      id: 11480,
      known_for_department: 'Acting',
      name: 'Frank Sivero',
      original_name: 'Frank Sivero',
      popularity: 10.377,
      profile_path: '/eqvhj0iNtcsN6EJhd21Goqi1DSq.jpg',
      cast_id: 97,
      character: 'Street Extra (uncredited)',
      credit_id: '55f1b81092514167140021b1',
      order: 54,
    },
    {
      adult: false,
      gender: 0,
      id: 1209678,
      known_for_department: 'Acting',
      name: 'Filomena Spagnuolo',
      original_name: 'Filomena Spagnuolo',
      popularity: 0.84,
      profile_path: null,
      cast_id: 98,
      character: 'Extra in Wedding Scene (uncredited)',
      credit_id: '55f1b83592514167140021c1',
      order: 55,
    },
    {
      adult: false,
      gender: 2,
      id: 78336,
      known_for_department: 'Directing',
      name: 'Nick Vallelonga',
      original_name: 'Nick Vallelonga',
      popularity: 1.31,
      profile_path: '/h0GwAHN1J5lDysqgWxMIg66LNBW.jpg',
      cast_id: 100,
      character: 'Wedding Party Guest (uncredited)',
      credit_id: '55f1b89b9251410d6d000af0',
      order: 56,
    },
    {
      adult: false,
      gender: 2,
      id: 16525,
      known_for_department: 'Acting',
      name: 'Joe Spinell',
      original_name: 'Joe Spinell',
      popularity: 3.145,
      profile_path: '/rdDEi8SJSx9OwVJQaHNa3VfZBRM.jpg',
      cast_id: 99,
      character: 'William "Willie" Cicci (uncredited)',
      credit_id: '55f1b85d925141670500228d',
      order: 57,
    },
    {
      adult: false,
      gender: 2,
      id: 1234848,
      known_for_department: 'Acting',
      name: 'Conrad Yama',
      original_name: 'Conrad Yama',
      popularity: 1.96,
      profile_path: null,
      cast_id: 101,
      character: 'Fruit Vendor (uncredited)',
      credit_id: '55f1b90892514167050022a8',
      order: 58,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 1776,
      known_for_department: 'Directing',
      name: 'Francis Ford Coppola',
      original_name: 'Francis Ford Coppola',
      popularity: 6.988,
      profile_path: '/mGKkVp3l9cipPt10AqoQnwaPrfI.jpg',
      credit_id: '52fe422bc3a36847f80093db',
      department: 'Writing',
      job: 'Screenplay',
    },
    {
      adult: false,
      gender: 2,
      id: 1776,
      known_for_department: 'Directing',
      name: 'Francis Ford Coppola',
      original_name: 'Francis Ford Coppola',
      popularity: 6.988,
      profile_path: '/mGKkVp3l9cipPt10AqoQnwaPrfI.jpg',
      credit_id: '5e92505cccb15f00136de455',
      department: 'Directing',
      job: 'Director',
    },
    {
      adult: false,
      gender: 2,
      id: 1776,
      known_for_department: 'Directing',
      name: 'Francis Ford Coppola',
      original_name: 'Francis Ford Coppola',
      popularity: 6.988,
      profile_path: '/mGKkVp3l9cipPt10AqoQnwaPrfI.jpg',
      credit_id: '5f9c86e3bc8abc003b2fe6b7',
      department: 'Crew',
      job: 'Thanks',
    },
    {
      adult: false,
      gender: 2,
      id: 2870,
      known_for_department: 'Production',
      name: 'Gray Frederickson',
      original_name: 'Gray Frederickson',
      popularity: 0.6,
      profile_path: null,
      credit_id: '53884fe1c3a3681ad7004590',
      department: 'Production',
      job: 'Associate Producer',
    },
    {
      adult: false,
      gender: 2,
      id: 2871,
      known_for_department: 'Production',
      name: 'Fred Roos',
      original_name: 'Fred Roos',
      popularity: 3.192,
      profile_path: '/qfXLY5E589l0TQnoayWmUrBDsgo.jpg',
      credit_id: '53885041c3a3681ad700459b',
      department: 'Production',
      job: 'Casting',
    },
    {
      adult: false,
      gender: 2,
      id: 2875,
      known_for_department: 'Art',
      name: 'Dean Tavoularis',
      original_name: 'Dean Tavoularis',
      popularity: 1.616,
      profile_path: '/hrRBaXUn2k29qd1MvAxuag5L32c.jpg',
      credit_id: '53884b4e0e0a261441005deb',
      department: 'Art',
      job: 'Production Design',
    },
    {
      adult: false,
      gender: 2,
      id: 457,
      known_for_department: 'Production',
      name: 'Albert S. Ruddy',
      original_name: 'Albert S. Ruddy',
      popularity: 1.721,
      profile_path: null,
      credit_id: '52fe422bc3a36847f80093cf',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      gender: 2,
      id: 949,
      known_for_department: 'Production',
      name: 'Louis DiGiaimo',
      original_name: 'Louis DiGiaimo',
      popularity: 1.62,
      profile_path: null,
      credit_id: '53885009c3a3682f780004c6',
      department: 'Production',
      job: 'Casting',
    },
    {
      adult: false,
      gender: 2,
      id: 3083,
      known_for_department: 'Writing',
      name: 'Mario Puzo',
      original_name: 'Mario Puzo',
      popularity: 2.157,
      profile_path: '/lEsT1uCZAZg1nYDQe3Fsj9CalzT.jpg',
      credit_id: '52fe422bc3a36847f80093d5',
      department: 'Writing',
      job: 'Screenplay',
    },
    {
      adult: false,
      gender: 2,
      id: 3083,
      known_for_department: 'Writing',
      name: 'Mario Puzo',
      original_name: 'Mario Puzo',
      popularity: 2.157,
      profile_path: '/lEsT1uCZAZg1nYDQe3Fsj9CalzT.jpg',
      credit_id: '538848cec3a3681aea00405a',
      department: 'Writing',
      job: 'Novel',
    },
    {
      adult: false,
      gender: 2,
      id: 3097,
      known_for_department: 'Camera',
      name: 'Gordon Willis',
      original_name: 'Gordon Willis',
      popularity: 2.456,
      profile_path: '/6gOmfatlF7UdhaHi2tPsZMb5vmz.jpg',
      credit_id: '538848a0c3a3681ae3004283',
      department: 'Camera',
      job: 'Director of Photography',
    },
    {
      adult: false,
      gender: 2,
      id: 3098,
      known_for_department: 'Sound',
      name: 'Nino Rota',
      original_name: 'Nino Rota',
      popularity: 3.192,
      profile_path: '/v42v3uM7jqwoZxDJ8MlEtT6Ol7a.jpg',
      credit_id: '538848b1c3a3681aea004056',
      department: 'Sound',
      job: 'Original Music Composer',
    },
    {
      adult: false,
      gender: 2,
      id: 3099,
      known_for_department: 'Editing',
      name: 'William Reynolds',
      original_name: 'William Reynolds',
      popularity: 0.6,
      profile_path: null,
      credit_id: '52fe422bc3a36847f80093ed',
      department: 'Editing',
      job: 'Editor',
    },
    {
      adult: false,
      gender: 2,
      id: 3100,
      known_for_department: 'Editing',
      name: 'Peter Zinner',
      original_name: 'Peter Zinner',
      popularity: 0.84,
      profile_path: null,
      credit_id: '52fe422bc3a36847f80093f3',
      department: 'Editing',
      job: 'Editor',
    },
    {
      adult: false,
      gender: 0,
      id: 3101,
      known_for_department: 'Production',
      name: 'Andrea Eastman',
      original_name: 'Andrea Eastman',
      popularity: 0.6,
      profile_path: null,
      credit_id: '53885029c3a3681ad7004596',
      department: 'Production',
      job: 'Casting',
    },
    {
      adult: false,
      gender: 2,
      id: 3103,
      known_for_department: 'Sound',
      name: 'Charles Grenzbach',
      original_name: 'Charles Grenzbach',
      popularity: 0.6,
      profile_path: null,
      credit_id: '570006ec9251417647000790',
      department: 'Sound',
      job: 'Sound Re-Recording Mixer',
    },
    {
      adult: false,
      gender: 2,
      id: 3104,
      known_for_department: 'Sound',
      name: 'Chris Newman',
      original_name: 'Chris Newman',
      popularity: 3.056,
      profile_path: null,
      credit_id: '569d53449251415e67004177',
      department: 'Sound',
      job: 'Sound',
    },
    {
      adult: false,
      gender: 2,
      id: 3105,
      known_for_department: 'Sound',
      name: 'Richard Portman',
      original_name: 'Richard Portman',
      popularity: 0.6,
      profile_path: null,
      credit_id: '568c060ac3a3685f89018710',
      department: 'Sound',
      job: 'Sound Re-Recording Mixer',
    },
    {
      adult: false,
      gender: 0,
      id: 3106,
      known_for_department: 'Sound',
      name: 'John C. Hammell',
      original_name: 'John C. Hammell',
      popularity: 0.6,
      profile_path: null,
      credit_id: '56cb4864c3a3684e2500045e',
      department: 'Sound',
      job: 'Music Editor',
    },
    {
      adult: false,
      gender: 2,
      id: 6099,
      known_for_department: 'Production',
      name: 'Valerio De Paolis',
      original_name: 'Valerio De Paolis',
      popularity: 0.6,
      profile_path: '/rbsYkbJPgQAMuFY71RYrYatdXWT.jpg',
      credit_id: '563e3d18c3a3681b5402d6d3',
      department: 'Production',
      job: 'Production Manager',
    },
    {
      adult: false,
      gender: 1,
      id: 6851,
      known_for_department: 'Costume & Make-Up',
      name: 'Anna Hill Johnstone',
      original_name: 'Anna Hill Johnstone',
      popularity: 0.7,
      profile_path: null,
      credit_id: '53884fc3c3a3681add0044ad',
      department: 'Costume & Make-Up',
      job: 'Costume Design',
    },
    {
      adult: false,
      gender: 0,
      id: 16194,
      known_for_department: 'Costume & Make-Up',
      name: 'Philip Leto',
      original_name: 'Philip Leto',
      popularity: 0.6,
      profile_path: null,
      credit_id: '56a76fd49251412a04002fa6',
      department: 'Costume & Make-Up',
      job: 'Hairstylist',
    },
    {
      adult: false,
      gender: 2,
      id: 10546,
      known_for_department: 'Production',
      name: 'Fred T. Gallo',
      original_name: 'Fred T. Gallo',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5e9250a3875d1a001442c342',
      department: 'Directing',
      job: 'Assistant Director',
    },
    {
      adult: false,
      gender: 0,
      id: 11789,
      known_for_department: 'Production',
      name: 'Fred C. Caruso',
      original_name: 'Fred C. Caruso',
      popularity: 1.712,
      profile_path: null,
      credit_id: '57447bba925141110900063d',
      department: 'Production',
      job: 'Unit Production Manager',
    },
    {
      adult: false,
      gender: 2,
      id: 12288,
      known_for_department: 'Production',
      name: 'Robert Evans',
      original_name: 'Robert Evans',
      popularity: 1.62,
      profile_path: '/rCiTT2VrBKeHWdnHAyfGtMXs9go.jpg',
      credit_id: '57447b41c3a36807770006ab',
      department: 'Production',
      job: 'Executive Producer',
    },
    {
      adult: false,
      gender: 0,
      id: 14059,
      known_for_department: 'Crew',
      name: 'Sass Bedig',
      original_name: 'Sass Bedig',
      popularity: 2.094,
      profile_path: null,
      credit_id: '57448523925141218f000400',
      department: 'Crew',
      job: 'Special Effects',
    },
    {
      adult: false,
      gender: 2,
      id: 29654,
      known_for_department: 'Costume & Make-Up',
      name: 'Dick Smith',
      original_name: 'Dick Smith',
      popularity: 1.491,
      profile_path: '/kKCenlQ8iQCTLGfX8ZPpJFpxvwS.jpg',
      credit_id: '56a76ff8c3a36819c9002fcb',
      department: 'Costume & Make-Up',
      job: 'Makeup Artist',
    },
    {
      adult: false,
      gender: 2,
      id: 30580,
      known_for_department: 'Art',
      name: 'Philip Smith',
      original_name: 'Philip Smith',
      popularity: 0.6,
      profile_path: null,
      credit_id: '53884fb2c3a3681ad700458c',
      department: 'Art',
      job: 'Set Decoration',
    },
    {
      adult: false,
      gender: 0,
      id: 81519,
      known_for_department: 'Art',
      name: 'Warren Clymer',
      original_name: 'Warren Clymer',
      popularity: 0.6,
      profile_path: null,
      credit_id: '53884f8dc3a3681add0044a6',
      department: 'Art',
      job: 'Art Direction',
    },
    {
      adult: false,
      gender: 0,
      id: 81532,
      known_for_department: 'Costume & Make-Up',
      name: 'George Newman',
      original_name: 'George Newman',
      popularity: 0.6,
      profile_path: null,
      credit_id: '574487b9c3a3680762000a52',
      department: 'Costume & Make-Up',
      job: 'Costume Supervisor',
    },
    {
      adult: false,
      gender: 0,
      id: 81533,
      known_for_department: 'Costume & Make-Up',
      name: 'Marilyn Putnam',
      original_name: 'Marilyn Putnam',
      popularity: 1.048,
      profile_path: null,
      credit_id: '57448872925141218f000515',
      department: 'Costume & Make-Up',
      job: 'Costume Design',
    },
    {
      adult: false,
      gender: 2,
      id: 51302,
      known_for_department: 'Crew',
      name: 'Joe Bucaro III',
      original_name: 'Joe Bucaro III',
      popularity: 5.651,
      profile_path: '/gvJs1YQZRrSbkiSGAiCAugaXyzl.jpg',
      credit_id: '574486e0c3a368076b000ac6',
      department: 'Crew',
      job: 'Stunts',
    },
    {
      adult: false,
      gender: 2,
      id: 96912,
      known_for_department: 'Crew',
      name: 'Joe Lombardi',
      original_name: 'Joe Lombardi',
      popularity: 1.012,
      profile_path: null,
      credit_id: '574485a9925141218f000420',
      department: 'Crew',
      job: 'Special Effects',
    },
    {
      adult: false,
      gender: 2,
      id: 718968,
      known_for_department: 'Production',
      name: 'Stephen F. Kesten',
      original_name: 'Stephen F. Kesten',
      popularity: 1.96,
      profile_path: null,
      credit_id: '5e9250b284448e00148f0783',
      department: 'Directing',
      job: 'Assistant Director',
    },
    {
      adult: false,
      gender: 2,
      id: 1318092,
      known_for_department: 'Crew',
      name: 'Paul J. Lombardi',
      original_name: 'Paul J. Lombardi',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5744865f92514120a70004b3',
      department: 'Visual Effects',
      job: 'Special Effects Supervisor',
    },
    {
      adult: false,
      gender: 2,
      id: 1433439,
      known_for_department: 'Crew',
      name: 'Paul Baxley',
      original_name: 'Paul Baxley',
      popularity: 2.578,
      profile_path: null,
      credit_id: '574486b4c3a3681c760004a9',
      department: 'Crew',
      job: 'Stunt Coordinator',
    },
    {
      adult: false,
      gender: 0,
      id: 1518601,
      known_for_department: 'Costume & Make-Up',
      name: 'Phil Rhodes',
      original_name: 'Phil Rhodes',
      popularity: 0.6,
      profile_path: null,
      credit_id: '56a76fc79251412a04002fa3',
      department: 'Costume & Make-Up',
      job: 'Makeup Artist',
    },
    {
      adult: false,
      gender: 2,
      id: 1546904,
      known_for_department: 'Camera',
      name: 'Robert Ward',
      original_name: 'Robert Ward',
      popularity: 0.98,
      profile_path: null,
      credit_id: '566871e5c3a36836ac0038f7',
      department: 'Camera',
      job: 'Grip',
    },
    {
      adult: false,
      gender: 0,
      id: 1547035,
      known_for_department: 'Production',
      name: 'Riccardo Bertoni',
      original_name: 'Riccardo Bertoni',
      popularity: 0.6,
      profile_path: null,
      credit_id: '57448778c3a3680777000a42',
      department: 'Production',
      job: 'Casting',
    },
    {
      adult: false,
      gender: 0,
      id: 1614958,
      known_for_department: 'Crew',
      name: 'Steven Burnett',
      original_name: 'Steven Burnett',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5744870d92514133d400001b',
      department: 'Crew',
      job: 'Stunts',
    },
    {
      adult: false,
      gender: 0,
      id: 1625346,
      known_for_department: 'Production',
      name: 'Ned Kopp',
      original_name: 'Ned Kopp',
      popularity: 0.6,
      profile_path: null,
      credit_id: '57447c09925141110f000695',
      department: 'Production',
      job: 'Production Manager',
    },
    {
      adult: false,
      gender: 2,
      id: 1625347,
      known_for_department: 'Directing',
      name: 'Tony Brandt',
      original_name: 'Tony Brandt',
      popularity: 0.6,
      profile_path: null,
      credit_id: '5e92510accb15f00156de8d4',
      department: 'Directing',
      job: 'Assistant Director',
    },
    {
      adult: false,
      gender: 0,
      id: 1789636,
      known_for_department: 'Sound',
      name: 'Carl Fortina',
      original_name: 'Carl Fortina',
      popularity: 0.6,
      profile_path: null,
      credit_id: '58e3cf17c3a3684aa40124b5',
      department: 'Sound',
      job: 'Musician',
    },
  ],
};
